# Generated by Django 4.0.3 on 2022-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
