# Generated by Django 4.0.3 on 2022-04-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('F', 'Free Plan'), ('S', 'Student Plam'), ('O', 'Organisation Plan')], default='F', max_length=50),
        ),
    ]
