# Generated by Django 4.0.3 on 2022-04-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_remove_subscription_id_alter_subscription_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='storage_used',
            field=models.IntegerField(default=0),
        ),
    ]
