# Generated by Django 4.0.3 on 2022-04-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_id',
        ),
    ]
