# Generated by Django 4.0.3 on 2022-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_subscription_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_plan',
        ),
    ]
