# Generated by Django 4.0.3 on 2022-04-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_subscription_subscription_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
