# Generated by Django 4.0.3 on 2022-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(max_length=50),
        ),
    ]
