# Generated by Django 4.0.4 on 2022-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(max_length=50)),
            ],
        ),
    ]
