# Generated by Django 4.0.4 on 2022-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(max_length=50)),
                ('storage_used', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
